let randNum = getRandInt();

const checkBtn = document.getElementById('check-btn');
const userInput = document.getElementById('guess');
const message = document.getElementById('game-message');
const main_background = document.getElementById('main');
const playAgainBtn = document.getElementById('play-again');
const scoreMsg = document.getElementById('score');

console.log(randNum);

let num_tries = 0;//number of times the user guessed
const max_tries = 10;//maximum num of tries
playAgainBtn.disabled = true;//disable again button at start of game
let high_score = 0;//highest score
const startingScore = 10; //starting score
let score = startingScore;
let gameOver_score = 0;
let game_over = false;
//min and max valid input
const min = 1;
const max = 20;

/*Check whether the player's guess matches the number generated by the game */
function checkButton(){
    //validate user input
    if(isNaN(userInput.value) || userInput.value < min || userInput.value > max ){
        message.textContent = "Input not valid";
        console.log(userInput.value);
    }
    else{
        console.log('checking number...')
    
        if(userInput.value == randNum){
            console.log('You guessed the right number!');
            message.textContent = 'You guessed the right number!';
            increaseScore();
            main_background.style.backgroundColor = '#006600';
            disableCheckBtn()
            enableAgainBtn()
        }else if(userInput.value > randNum){
            console.log('You guessed too high');
            message.textContent = 'You guessed too high';
            updateNumTries();
            deductScore();
            main_background.style.backgroundColor = '#cc0000';
        }else if(userInput.value < randNum){
            console.log('You guessed low');
            message.textContent = 'You guessed too low';
            updateNumTries();
            deductScore();
            main_background.style.backgroundColor = '#cc7a00';
        }
        showScore(); 
        
        //check for game over before next guess
        game_over = isTen(max_tries);
        console.log(game_over);

        if(game_over || score ==  gameOver_score){
            gameOver();
        }

    }
    
}

function getRandInt(){
   //number generated by game
    return Math.floor(Math.random() * 20 + 1);
}

/*allow the player to play the game again */
function playAgain(){
    let game_over = isTen(max_tries);
    disableAgainBtn();
    resetInput();
    console.log(num_tries);
    if(game_over){
        resetScore(startingScore);
        resetNumTries();
    }
    showScore();
    resetGameMsg();
    resetBackground();
    enableCheckBtn();
    
    randNum = getRandInt();
    console.log(randNum);
}

/*reset number of tries */
function resetNumTries(){
    num_tries = 0;
}

/*reset user input*/
function resetInput(){
    userInput.value = "";
}

/*reset game message */
function resetGameMsg(){
    message.textContent = "Start guessing...";
}

/*reset main section background color */
function resetBackground(){
    main_background.style.backgroundColor = '#262626';
}

/*indicate game over */
function gameOver(){
    message.textContent = 'GAME OVER!! 😥';
    showScore();
    disableCheckBtn();
    enableAgainBtn();
}

/*reset score */
function resetScore(reset){
    score = reset;
}

/*display score */
function showScore(){
    scoreMsg.textContent = score;
}

/*deduct score when player guesses the wrong number*/
function deductScore(){
    score -= 1;
}

/*increase score when player guesses the right number*/
function increaseScore(){
    score += 10;
}

/*Check the value of num_tries*/
function isTen(max_tries){
    if(num_tries < max_tries){
        return false;
    }
    else{
        return true;
    }
}

/*if num_tries < 10, add 1 to it's value*/
function updateNumTries(){
    num_tries++;
    console.log(num_tries);

}

/*Enable check button at play again*/
function enableCheckBtn(){
    checkBtn.disabled = false;
}

/*Disable check button at game over*/
function disableCheckBtn(){
    checkBtn.disabled = true;
}

/*disable again button */
function disableAgainBtn(){
    playAgainBtn.disabled = true;
}

/*Enbale again button at game over*/ 
function enableAgainBtn(){
    playAgainBtn.disabled = false;
}

checkBtn.addEventListener('click', checkButton);
playAgainBtn.addEventListener('click', playAgain);

//TODO: keep track of high score
