const randNum = Math.floor(Math.random() * 20);//number generated by game

const checkBtn = document.getElementById('check-btn');
const userInput = document.getElementById('guess');
const message = document.getElementById('game-message');
const main_background = document.getElementById('main');
const playAgainBtn = document.getElementById('play-again');

console.log(randNum);

let num_tries = 0;//number of times the user guessed
playAgainBtn.disabled = true;//disable again button at start of game

/*Check whether the player's guess matches the number generated by the game */
function checkButton(){
    const max_tries = 10;
    let game_over = isTen(max_tries);

    //if num_tries is maxed; game over!, then disable check button
    if(game_over){
        message.textContent = 'GAME OVER!! 😥';
        checkBtn.disabled = true;
        enableAgainBtn();
    }
    else{
        updateNumTries();
        console.log('checking number...')
        if(userInput.value == randNum){
            console.log('You guessed the right number!');
            message.textContent = 'You guessed the right number!';
            main_background.style.backgroundColor = '#006600';
        }else if(userInput.value > randNum){
            console.log('You guessed too high');
            message.textContent = 'You guessed too high';
            main_background.style.backgroundColor = '#cc0000';
        }else if(userInput.value < randNum){
            console.log('You guessed low');
            message.textContent = 'You guessed too low';
            main_background.style.backgroundColor = '#cc7a00';
        }
    }
    
}

/*Check the value of num_tries*/
function isTen(max_tries){
    if(num_tries < max_tries){
        return false;
    }
    else{
        return true;
    }
}

/*if num_tries < 10, add 1 to it's value*/
function updateNumTries(){
    ++num_tries;

}

/*Enbale again button at game over*/ 
function enableAgainBtn(){
    playAgainBtn.disabled = false;
}

//once player presses play again button, reset userInput and game-message, give main background it's original color
checkBtn.addEventListener('click', checkButton);